/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DTOs.MovieDTO;

/**
 *
 * @author Java @Xiumin
 */
public class MovieViewer extends javax.swing.JFrame {

    MovieDTO movie = new MovieDTO();
    /**
     * Creates new form MovieViewer
     */
    public MovieViewer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        logoScrollPane = new javax.swing.JScrollPane();
        logoLabel = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        recentReleasesMovie2ScrollPane = new javax.swing.JScrollPane();
        recentReleasesMovie2Label = new javax.swing.JLabel();
        recentReleasesMovie1ScrollPane = new javax.swing.JScrollPane();
        recentReleasesMovie1Label = new javax.swing.JLabel();
        recentReleasesMovie3ScrollPane = new javax.swing.JScrollPane();
        recentReleasesMovie3Label = new javax.swing.JLabel();
        recentReleasesMovie4ScrollPane = new javax.swing.JScrollPane();
        recentReleasesMovie4Label = new javax.swing.JLabel();
        recentReleasesMovie6ScrollPane = new javax.swing.JScrollPane();
        recentReleasesMovie6Label = new javax.swing.JLabel();
        recentReleasesMovie5ScrollPane = new javax.swing.JScrollPane();
        recentReleasesMovie5Label = new javax.swing.JLabel();
        allTimeFamousMovie5ScrollPane = new javax.swing.JScrollPane();
        allTimeFamousMovie5Label = new javax.swing.JLabel();
        allTimeFamousMovie6ScrollPane = new javax.swing.JScrollPane();
        allTimeFamousMovie6Label = new javax.swing.JLabel();
        allTimeFamousMovie4ScrollPane = new javax.swing.JScrollPane();
        allTimeFamousMovie4Label = new javax.swing.JLabel();
        allTimeFamousMovie1ScrollPane = new javax.swing.JScrollPane();
        allTimeFamousMovie1Label = new javax.swing.JLabel();
        allTimeFamousMovie3ScrollPane = new javax.swing.JScrollPane();
        allTimeFamousMovie3Label = new javax.swing.JLabel();
        allTimeFamousMovie2ScrollPane = new javax.swing.JScrollPane();
        allTimeFamousMovie2Label = new javax.swing.JLabel();
        allTimeFamousHeadingPanel = new javax.swing.JPanel();
        allTimeFamousHeadingLabel = new javax.swing.JLabel();
        recentReleasesHeadingPanel = new javax.swing.JPanel();
        recentReleasesHeadingLabel = new javax.swing.JLabel();
        allTimeFamousHeadingPanel1 = new javax.swing.JPanel();
        allTimeFamousHeadingLabel1 = new javax.swing.JLabel();
        allTimeFamousMovie2ScrollPane1 = new javax.swing.JScrollPane();
        allTimeFamousMovie2Label1 = new javax.swing.JLabel();
        allTimeFamousMovie3ScrollPane1 = new javax.swing.JScrollPane();
        allTimeFamousMovie3Label1 = new javax.swing.JLabel();
        allTimeFamousMovie1ScrollPane1 = new javax.swing.JScrollPane();
        allTimeFamousMovie1Label1 = new javax.swing.JLabel();
        allTimeFamousMovie4ScrollPane1 = new javax.swing.JScrollPane();
        allTimeFamousMovie4Label1 = new javax.swing.JLabel();
        allTimeFamousMovie6ScrollPane1 = new javax.swing.JScrollPane();
        allTimeFamousMovie6Label1 = new javax.swing.JLabel();
        allTimeFamousMovie5ScrollPane1 = new javax.swing.JScrollPane();
        allTimeFamousMovie5Label1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1362, 730));
        setMinimumSize(new java.awt.Dimension(1362, 730));
        setPreferredSize(new java.awt.Dimension(1362, 730));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1365, 728));
        jPanel1.setMinimumSize(new java.awt.Dimension(1365, 728));
        jPanel1.setPreferredSize(new java.awt.Dimension(1365, 728));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1362, 730));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1362, 730));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1350, 690));

        jPanel2.setBackground(new java.awt.Color(138, 6, 81));
        jPanel2.setMaximumSize(new java.awt.Dimension(1365, 728));
        jPanel2.setMinimumSize(new java.awt.Dimension(1365, 728));

        logoScrollPane.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/logo.png"))); // NOI18N
        logoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logoScrollPane.setViewportView(logoLabel);

        namePanel.setBackground(new java.awt.Color(138, 6, 81));
        namePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 255), java.awt.Color.white));
        namePanel.setForeground(new java.awt.Color(255, 204, 0));
        namePanel.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("vtks morning rain 3D", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Movies");

        jLabel2.setFont(new java.awt.Font("vtks morning rain 3D", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Recommendation Engine");

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        searchTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchTextField.setText(" Type here to Search...");

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/search.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        recentReleasesMovie2ScrollPane.setViewportView(recentReleasesMovie2Label);

        recentReleasesMovie1ScrollPane.setViewportView(recentReleasesMovie1Label);

        recentReleasesMovie3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/onLoad2(small).gif"))); // NOI18N
        recentReleasesMovie3ScrollPane.setViewportView(recentReleasesMovie3Label);

        recentReleasesMovie4ScrollPane.setViewportView(recentReleasesMovie4Label);

        recentReleasesMovie6ScrollPane.setViewportView(recentReleasesMovie6Label);

        recentReleasesMovie5ScrollPane.setViewportView(recentReleasesMovie5Label);

        allTimeFamousMovie5ScrollPane.setViewportView(allTimeFamousMovie5Label);

        allTimeFamousMovie6ScrollPane.setViewportView(allTimeFamousMovie6Label);

        allTimeFamousMovie4ScrollPane.setViewportView(allTimeFamousMovie4Label);

        allTimeFamousMovie1ScrollPane.setViewportView(allTimeFamousMovie1Label);

        allTimeFamousMovie3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/onLoad2(small).gif"))); // NOI18N
        allTimeFamousMovie3ScrollPane.setViewportView(allTimeFamousMovie3Label);

        allTimeFamousMovie2ScrollPane.setViewportView(allTimeFamousMovie2Label);

        allTimeFamousHeadingPanel.setBackground(new java.awt.Color(66, 66, 66));
        allTimeFamousHeadingPanel.setForeground(new java.awt.Color(255, 255, 255));

        allTimeFamousHeadingLabel.setBackground(new java.awt.Color(66, 66, 66));
        allTimeFamousHeadingLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        allTimeFamousHeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        allTimeFamousHeadingLabel.setText(" More From This Director...");

        javax.swing.GroupLayout allTimeFamousHeadingPanelLayout = new javax.swing.GroupLayout(allTimeFamousHeadingPanel);
        allTimeFamousHeadingPanel.setLayout(allTimeFamousHeadingPanelLayout);
        allTimeFamousHeadingPanelLayout.setHorizontalGroup(
            allTimeFamousHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allTimeFamousHeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        allTimeFamousHeadingPanelLayout.setVerticalGroup(
            allTimeFamousHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allTimeFamousHeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        recentReleasesHeadingPanel.setBackground(new java.awt.Color(66, 66, 66));
        recentReleasesHeadingPanel.setForeground(new java.awt.Color(255, 255, 255));

        recentReleasesHeadingLabel.setBackground(new java.awt.Color(66, 66, 66));
        recentReleasesHeadingLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        recentReleasesHeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        recentReleasesHeadingLabel.setText(" Similar Movies...");

        javax.swing.GroupLayout recentReleasesHeadingPanelLayout = new javax.swing.GroupLayout(recentReleasesHeadingPanel);
        recentReleasesHeadingPanel.setLayout(recentReleasesHeadingPanelLayout);
        recentReleasesHeadingPanelLayout.setHorizontalGroup(
            recentReleasesHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentReleasesHeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        recentReleasesHeadingPanelLayout.setVerticalGroup(
            recentReleasesHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentReleasesHeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        allTimeFamousHeadingPanel1.setBackground(new java.awt.Color(66, 66, 66));
        allTimeFamousHeadingPanel1.setForeground(new java.awt.Color(255, 255, 255));

        allTimeFamousHeadingLabel1.setBackground(new java.awt.Color(66, 66, 66));
        allTimeFamousHeadingLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        allTimeFamousHeadingLabel1.setForeground(new java.awt.Color(255, 255, 255));
        allTimeFamousHeadingLabel1.setText("More From This Writer...");

        javax.swing.GroupLayout allTimeFamousHeadingPanel1Layout = new javax.swing.GroupLayout(allTimeFamousHeadingPanel1);
        allTimeFamousHeadingPanel1.setLayout(allTimeFamousHeadingPanel1Layout);
        allTimeFamousHeadingPanel1Layout.setHorizontalGroup(
            allTimeFamousHeadingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allTimeFamousHeadingLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        allTimeFamousHeadingPanel1Layout.setVerticalGroup(
            allTimeFamousHeadingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allTimeFamousHeadingLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        allTimeFamousMovie2ScrollPane1.setViewportView(allTimeFamousMovie2Label1);

        allTimeFamousMovie3Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/onLoad2(small).gif"))); // NOI18N
        allTimeFamousMovie3ScrollPane1.setViewportView(allTimeFamousMovie3Label1);

        allTimeFamousMovie1ScrollPane1.setViewportView(allTimeFamousMovie1Label1);

        allTimeFamousMovie4ScrollPane1.setViewportView(allTimeFamousMovie4Label1);

        allTimeFamousMovie6ScrollPane1.setViewportView(allTimeFamousMovie6Label1);

        allTimeFamousMovie5ScrollPane1.setViewportView(allTimeFamousMovie5Label1);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("Avatar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel5.setText("Tagline");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Image Here...");
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white)));
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane3.setViewportView(jLabel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(452, 452, 452))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(logoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(allTimeFamousMovie1ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(allTimeFamousMovie2ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(allTimeFamousMovie3ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(allTimeFamousMovie4ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(allTimeFamousMovie5ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(allTimeFamousMovie6ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(allTimeFamousMovie1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(allTimeFamousMovie2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(allTimeFamousMovie3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(allTimeFamousMovie4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(allTimeFamousMovie5ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(allTimeFamousMovie6ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(recentReleasesMovie1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(recentReleasesMovie2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(recentReleasesMovie3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(recentReleasesMovie4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(recentReleasesMovie5ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(recentReleasesMovie6ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allTimeFamousHeadingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allTimeFamousHeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recentReleasesHeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(recentReleasesHeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recentReleasesMovie2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentReleasesMovie1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentReleasesMovie4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentReleasesMovie3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentReleasesMovie6ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentReleasesMovie5ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(allTimeFamousHeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allTimeFamousMovie6ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie5ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(allTimeFamousHeadingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allTimeFamousMovie2ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie1ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie4ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie3ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie6ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeFamousMovie5ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1350, 728);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allTimeFamousHeadingLabel;
    private javax.swing.JLabel allTimeFamousHeadingLabel1;
    private javax.swing.JPanel allTimeFamousHeadingPanel;
    private javax.swing.JPanel allTimeFamousHeadingPanel1;
    private javax.swing.JLabel allTimeFamousMovie1Label;
    private javax.swing.JLabel allTimeFamousMovie1Label1;
    private javax.swing.JScrollPane allTimeFamousMovie1ScrollPane;
    private javax.swing.JScrollPane allTimeFamousMovie1ScrollPane1;
    private javax.swing.JLabel allTimeFamousMovie2Label;
    private javax.swing.JLabel allTimeFamousMovie2Label1;
    private javax.swing.JScrollPane allTimeFamousMovie2ScrollPane;
    private javax.swing.JScrollPane allTimeFamousMovie2ScrollPane1;
    private javax.swing.JLabel allTimeFamousMovie3Label;
    private javax.swing.JLabel allTimeFamousMovie3Label1;
    private javax.swing.JScrollPane allTimeFamousMovie3ScrollPane;
    private javax.swing.JScrollPane allTimeFamousMovie3ScrollPane1;
    private javax.swing.JLabel allTimeFamousMovie4Label;
    private javax.swing.JLabel allTimeFamousMovie4Label1;
    private javax.swing.JScrollPane allTimeFamousMovie4ScrollPane;
    private javax.swing.JScrollPane allTimeFamousMovie4ScrollPane1;
    private javax.swing.JLabel allTimeFamousMovie5Label;
    private javax.swing.JLabel allTimeFamousMovie5Label1;
    private javax.swing.JScrollPane allTimeFamousMovie5ScrollPane;
    private javax.swing.JScrollPane allTimeFamousMovie5ScrollPane1;
    private javax.swing.JLabel allTimeFamousMovie6Label;
    private javax.swing.JLabel allTimeFamousMovie6Label1;
    private javax.swing.JScrollPane allTimeFamousMovie6ScrollPane;
    private javax.swing.JScrollPane allTimeFamousMovie6ScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel logoLabel;
    public javax.swing.JScrollPane logoScrollPane;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel recentReleasesHeadingLabel;
    private javax.swing.JPanel recentReleasesHeadingPanel;
    private javax.swing.JLabel recentReleasesMovie1Label;
    private javax.swing.JScrollPane recentReleasesMovie1ScrollPane;
    private javax.swing.JLabel recentReleasesMovie2Label;
    private javax.swing.JScrollPane recentReleasesMovie2ScrollPane;
    private javax.swing.JLabel recentReleasesMovie3Label;
    private javax.swing.JScrollPane recentReleasesMovie3ScrollPane;
    private javax.swing.JLabel recentReleasesMovie4Label;
    private javax.swing.JScrollPane recentReleasesMovie4ScrollPane;
    private javax.swing.JLabel recentReleasesMovie5Label;
    private javax.swing.JScrollPane recentReleasesMovie5ScrollPane;
    private javax.swing.JLabel recentReleasesMovie6Label;
    private javax.swing.JScrollPane recentReleasesMovie6ScrollPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
